### ISSUE TITLE
Racket GUIs crash on start

### ISSUE THREAD

**Issue by AMDphreak** [racket/racket7#21]
Running DrRacket or any other GUI app fails on start. They are not compatible with latest macOS 10.14.2

**Comment by mflatt** [comment]
A few users have reported problems getting Finder to trust executables from our main distribution site. (It's not clear why, since both the disk image and the executables are signed. We'll keep trying to figure it out.) If that's the problem that you're seeing, you could try command-dragging the DrRacket executable out of its folder and then dragging it back. That back-and-forth may sound crazy, but it's a way of telling Finder that you trust the executable, and then the OS will run it without an extra layer of sandboxing.

If that's not it, can you say more about where you got the Racket installation and what you see when you try to run programs?

**Comment by rmculpepper** [comment]
@AMDphreak @mflatt The output of the following commands might be useful:

    spctl --status --verbose
    spctl --assess --verbose PATH/TO/DrRacket.app

where PATH/TO/DrRacket.app is a version of DrRacket that currently fails to run from Finder.

Reference: man page for spctl at https://www.unix.com/man-page/all/8/spctl/

**Comment by AMDphreak** [comment]
@mflatt that work-around worked. Any way we can get an official binary with this resolved? Feel like this problem is a major deterrent to picking up Racket.

**Comment by mflatt** [comment]
I'm so far stumped. Does v7.2 have the same problem? (It's signed with a different and newer certificate.)

**Comment by AMDphreak** [comment]
> I'm so far stumped. Does v7.2 have the same problem? (It's signed with a different and newer certificate.)

No, I tested the 7.1.0.xxx download, and it ran correctly, without having to force macOS to accept the signature.

**Comment by samth** [comment]
This repository is now archived, and issues should be reported to https://github.com/racket/racket.
